import type { Metadata } from "next";
import { poppins } from "./fonts";
import ReduxProvider from "@/redux/ReduxProvider";
import NextTopLoader from 'nextjs-toploader'

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${poppins.className}`}>
                <NextTopLoader showSpinner={false} />
                <ReduxProvider>
                    {children}
                </ReduxProvider>
            </body>
        </html>
    );
}
